version: '2'
services:
  nginx:
    build: .
    ports:
      - 4001:80
    volumes:
      - ./default.conf.template:/etc/nginx/conf.d/default.conf.template
    environment:
      TARGET: https://staging.cryptofacil.com
      ORIGIN: http://localhost:4000

